/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.parser.antlr;

import com.google.inject.Inject;
import fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.parser.antlr.internal.InternalConcurrLangParser;
import fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.services.ConcurrLangGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ConcurrLangParser extends AbstractAntlrParser {

	@Inject
	private ConcurrLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalConcurrLangParser createParser(XtextTokenStream stream) {
		return new InternalConcurrLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ConcurrLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ConcurrLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
