/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConcurrLangRuntimeModule extends AbstractConcurrLangRuntimeModule {
}
