/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ConcurrLangStandaloneSetup extends ConcurrLangStandaloneSetupGenerated {

	public static void doSetup() {
		new ConcurrLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
