/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.ide;


/**
 * Use this class to register ide components.
 */
public class ConcurrLangIdeModule extends AbstractConcurrLangIdeModule {
}
