/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.ConcurrLangRuntimeModule;
import fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.ConcurrLangStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ConcurrLangIdeSetup extends ConcurrLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ConcurrLangRuntimeModule(), new ConcurrLangIdeModule()));
	}
	
}
