/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.ui;

import com.google.inject.Injector;
import fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.ui.internal.ConcurrlangActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConcurrLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ConcurrlangActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ConcurrlangActivator activator = ConcurrlangActivator.getInstance();
		return activator != null ? activator.getInjector(ConcurrlangActivator.FR_UNIVCOTEDAZUR_I3S_KAIROS_MOCCML_EXAMPLE_CONCURRLANG_CONCURRLANG) : null;
	}

}
