/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.ui.tests;

import com.google.inject.Injector;
import fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.ui.internal.ConcurrlangActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ConcurrLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ConcurrlangActivator.getInstance().getInjector("fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.ConcurrLang");
	}

}
