/*
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ConcurrLangUiModule extends AbstractConcurrLangUiModule {

	public ConcurrLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
