/**
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.ConcurrLangFactory
 * @model kind="package"
 * @generated
 */
public interface ConcurrLangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "concurrLang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.univcotedazur.fr/i3s/kairos/moccml/example/concurrlang/ConcurrLang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "concurrLang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ConcurrLangPackage eINSTANCE = fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ModelImpl
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.StatementsImpl <em>Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.StatementsImpl
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getStatements()
   * @generated
   */
  int STATEMENTS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS__NAME = 0;

  /**
   * The number of structural features of the '<em>Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.JoinImpl <em>Join</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.JoinImpl
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getJoin()
   * @generated
   */
  int JOIN = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOIN__NAME = STATEMENTS__NAME;

  /**
   * The feature id for the '<em><b>Fork</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOIN__FORK = STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Join</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOIN_FEATURE_COUNT = STATEMENTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ForkImpl <em>Fork</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ForkImpl
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getFork()
   * @generated
   */
  int FORK = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORK__NAME = STATEMENTS__NAME;

  /**
   * The feature id for the '<em><b>Parent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORK__PARENT = STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Child</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORK__CHILD = STATEMENTS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Fork</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORK_FEATURE_COUNT = STATEMENTS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.BlockImpl
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__NAME = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ActionImpl
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getAction()
   * @generated
   */
  int ACTION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = STATEMENTS__NAME;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = STATEMENTS_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for class '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Statements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statements</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Statements
   * @generated
   */
  EClass getStatements();

  /**
   * Returns the meta object for the attribute '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Statements#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Statements#getName()
   * @see #getStatements()
   * @generated
   */
  EAttribute getStatements_Name();

  /**
   * Returns the meta object for class '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Join <em>Join</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Join</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Join
   * @generated
   */
  EClass getJoin();

  /**
   * Returns the meta object for the reference '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Join#getFork <em>Fork</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Fork</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Join#getFork()
   * @see #getJoin()
   * @generated
   */
  EReference getJoin_Fork();

  /**
   * Returns the meta object for class '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Fork <em>Fork</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fork</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Fork
   * @generated
   */
  EClass getFork();

  /**
   * Returns the meta object for the containment reference '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Fork#getParent <em>Parent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parent</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Fork#getParent()
   * @see #getFork()
   * @generated
   */
  EReference getFork_Parent();

  /**
   * Returns the meta object for the containment reference '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Fork#getChild <em>Child</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Child</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Fork#getChild()
   * @see #getFork()
   * @generated
   */
  EReference getFork_Child();

  /**
   * Returns the meta object for class '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for the attribute '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Block#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Block#getName()
   * @see #getBlock()
   * @generated
   */
  EAttribute getBlock_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Block#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Block#getStatements()
   * @see #getBlock()
   * @generated
   */
  EReference getBlock_Statements();

  /**
   * Returns the meta object for class '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ConcurrLangFactory getConcurrLangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ModelImpl
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.StatementsImpl <em>Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.StatementsImpl
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getStatements()
     * @generated
     */
    EClass STATEMENTS = eINSTANCE.getStatements();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENTS__NAME = eINSTANCE.getStatements_Name();

    /**
     * The meta object literal for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.JoinImpl <em>Join</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.JoinImpl
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getJoin()
     * @generated
     */
    EClass JOIN = eINSTANCE.getJoin();

    /**
     * The meta object literal for the '<em><b>Fork</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOIN__FORK = eINSTANCE.getJoin_Fork();

    /**
     * The meta object literal for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ForkImpl <em>Fork</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ForkImpl
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getFork()
     * @generated
     */
    EClass FORK = eINSTANCE.getFork();

    /**
     * The meta object literal for the '<em><b>Parent</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORK__PARENT = eINSTANCE.getFork_Parent();

    /**
     * The meta object literal for the '<em><b>Child</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORK__CHILD = eINSTANCE.getFork_Child();

    /**
     * The meta object literal for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.BlockImpl
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOCK__NAME = eINSTANCE.getBlock_Name();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__STATEMENTS = eINSTANCE.getBlock_Statements();

    /**
     * The meta object literal for the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ActionImpl
     * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.impl.ConcurrLangPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

  }

} //ConcurrLangPackage
