/**
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fork</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Fork#getForkedBlocks <em>Forked Blocks</em>}</li>
 * </ul>
 *
 * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.ConcurrLangPackage#getFork()
 * @model
 * @generated
 */
public interface Fork extends Statements
{
  /**
   * Returns the value of the '<em><b>Forked Blocks</b></em>' containment reference list.
   * The list contents are of type {@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Block}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forked Blocks</em>' containment reference list.
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.ConcurrLangPackage#getFork_ForkedBlocks()
   * @model containment="true"
   * @generated
   */
  EList<Block> getForkedBlocks();

} // Fork
