/**
 * generated by Xtext 2.25.0
 */
package fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Join</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Join#getFork <em>Fork</em>}</li>
 * </ul>
 *
 * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.ConcurrLangPackage#getJoin()
 * @model
 * @generated
 */
public interface Join extends Statements
{
  /**
   * Returns the value of the '<em><b>Fork</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fork</em>' reference.
   * @see #setFork(Fork)
   * @see fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.ConcurrLangPackage#getJoin_Fork()
   * @model
   * @generated
   */
  Fork getFork();

  /**
   * Sets the value of the '{@link fr.univcotedazur.i3s.kairos.moccml.example.concurrlang.concurrLang.Join#getFork <em>Fork</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fork</em>' reference.
   * @see #getFork()
   * @generated
   */
  void setFork(Fork value);

} // Join
